insert into todos (title, description, complete, user_id, category_id) values ('Die Hard 2', 'Duis consequat dui nec nisi volutpat eleifend.', true, 9, 1);
insert into todos (title, description, complete, user_id, category_id) values ('Man Called Gannon', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', true, 3, 1);
insert into todos (title, description, complete, user_id, category_id) values ('Brazilian Western (Faroeste Caboclo)', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', true, 1, 1);
insert into todos (title, description, complete, user_id, category_id) values ('Kind Lady', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true, 9, 1);
insert into todos (title, description, complete, user_id, category_id) values ('Chef''s Hen Kitchen', 'In hac habitasse platea dictumst.', false, 4, 2);
insert into todos (title, description, complete, user_id, category_id) values ('Plaid Tap Bar and Grill', 'Curabitur in libero ut massa volutpat convallis.', true, 7, 2);
insert into todos (title, description, complete, user_id, category_id) values ('The Sails Place', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', false, 4, 2);
insert into todos (title, description, complete, user_id, category_id) values ('Fabled Tiger Café', 'In hac habitasse platea dictumst.', true, 10, 2);
insert into todos (title, description, complete, user_id, category_id) values ('Small Plank Eatery', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', false, 2, 2);
insert into todos (title, description, complete, user_id, category_id) values ('The Alchemy of Mystery', 'Pellentesque ultrices mattis odio. Nulla suscipit ligula in lacus.', true, 3, 3);
insert into todos (title, description, complete, user_id, category_id) values ('Something Is Happening (Kuch Kuch Hota Hai)', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', true, 3, 3);
insert into todos (title, description, complete, user_id, category_id) values ('Again the Brave', 'In hac habitasse platea dictumst.', false, 6, 3);
insert into todos (title, description, complete, user_id, category_id) values ('Stranger on the Water', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', false, 10, 3);
insert into todos (title, description, complete, user_id, category_id) values ('Promised Threads', 'Morbi vestibulum, velit id pretium iaculis. Aliquam quis turpis eget elit sodales scelerisque.', false, 3, 3);
insert into todos (title, description, complete, user_id, category_id) values ('Kindle', 'Aenean fermentum.', true, 6, 4);
insert into todos (title, description, complete, user_id, category_id) values ('Fiddle-de-dee', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', false, 10, 4);
insert into todos (title, description, complete, user_id, category_id) values ('fanny pack', 'Nulla ac enim. In tempor,vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', true, 9, 4);
insert into todos (title, description, complete, user_id, category_id) values ('Gund Pusheen - Classic Pose Gray Plush Pusheen Stuffed Cat ', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', true, 2, 4);
insert into todos (title, description, complete, user_id, category_id) values ('Vintage Square Sunglasses', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', true, 10, 4);
insert into todos (title, description, complete, user_id, category_id) values ('Lorem ipsum dolor sit ame', 'Suspendisse accumsan tortor quis turpis.', false, 2, NULL);
insert into todos (title, description, complete, user_id, category_id) values ('Delirium', 'Suspendisse accumsan tortor quis turpis.', false, 2, NULL);
insert into todos (title, description, complete, user_id, category_id) values ('Excepteur sint occaecat cupidatat non proident', 'Sed ut perspiciatis unde omnis iste natus error sit.', false, 2, NULL);
